- hosts: all
  remote_user: vagrant
  become: true
  become_user: root
  become_method: sudo

  tasks:

#############################################################################

###
### ELK repository
###

# version 6
  - name: Add / enable the Elasticsearch repo
    yum_repository:
      name: elasticsearch-6.x
      description: Elastic repo for 6.x
      baseurl: https://artifacts.elastic.co/packages/6.x/yum
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      file: elasticsearch
      gpgcheck: yes
      enabled: yes


#############################################################################

###
### Install Elasticsearch, Logstash and Kibana, prerequisites and enable them
###

  - name: Installing elasticsearch CORE components
    yum:
       name: "{{ item }}"
       state: latest
       update_cache: yes
    with_items:
       - java-1.8.0-openjdk
       - net-tools
       - elasticsearch
       - logstash
       - kibana
       - jq
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"

  - debug:
      msg: "Getting the CORE services up and running..."

  - name: Start and enable services at boot time
    service:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - elasticsearch
       - logstash
       - kibana
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"

#############################################################################
###
### Install beats and enable them
###

  - name: Installing elastic beats
    yum:
       name: "{{ item }}"
       state: latest
       update_cache: yes
    with_items:
       - filebeat
       - heartbeat-elastic
       - metricbeat
       - packetbeat
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"

  - debug:
      msg: "Getting the BEATS up and running..."

  - name: Start and enable services at boot time
    service:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - filebeat
       - heartbeat-elastic
       - metricbeat
       - packetbeat
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"

#############################################################################
