###
### Set up the following:
### * TLS: on ALL nodes that are part of the cluster
### * FILE realm:  administrator users on ALL nodes part of the cluster
###                (create users and users_roles files only, )
###

- hosts:         es_masternodes, es_datanodes, es_clientnodes, es_machinelearningnodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars_files:
  - group_vars/all
  - group_vars/tls

  roles:
    # Set up TLS for transport protocol on ALL cluster nodes
    - role: role_tls
    - role: role_filerealm
