###
### Set up Logstashnodes
###


- hosts:          es_logstashnodes
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

  vars_files:
  - group_vars/all
  - group_vars/logstashnodes

  roles:
    - role: role_logstash
