###
### Set up Kibananodes
###

- hosts:          es_kibananodes
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

  vars_files:
  - group_vars/all
  - group_vars/kibananodes
  
  roles:
    - role: role_kibana
