###
### Set up the following:
### * initial cluster with the masternodes
###

- hosts:         es_masternodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars_files:
  - group_vars/all
  - group_vars/masternodes
  - group_vars/tls

  roles:
    # Masternode only runs Elasticsearch as master-eligable node
    - role: role_masternodes
