###
### Set up the following:
### * TLS: on ALL nodes that are part of the cluster
### * FILE realm:  administrator users on ALL nodes part of the cluster
###                (create users and users_roles files only, )
###

- hosts:         es_masternodes, es_datanodes, es_clientnodes, es_machinelearningnodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars:

    # Ownership and permissions for configfiles
    owner: "root"
    group: "elasticsearch"

    # TLS parameters
    #
    # zip archive name with P12 file
    elastic_ca_archive_name: "elasticstack"
    elastic_ca_password: "1234"

    ### Useraccounts in filerealm!
    username_es_administrator: "es_administrator"
    password_es_administrator: "es_administrator"

  roles:
    # Set up TLS for transport protocol on ALL cluster nodes
    - role: role_tls
    - role: role_filerealm
