###
### Set up Logstashnodes
###


- hosts:          es_logstashnodes
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

  vars:
    es_data_ports:         "9200"
    es_data_hosts:         "{{ groups['es_datanodes'] | to_json }}"

  roles:
    - role: role_logstash
