- hosts:         es_masternodes, es_datanodes, es_clientnodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars:

    # Ownership and permissions for configfiles
    owner: "root"
    group: "elasticsearch"

    # TLS parameters
    #
    # zip archive name with P12 file
    elastic_ca_archive_name: "elasticstack"
    elastic_ca_password: "1234"


  roles:
    # Set up TLS for transport protocol on ALL cluster nodes
    - role: role_tls



- hosts:         es_masternodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars:

    # Basic settings
    clustername:              "cluster_dc1_dev"
    path_data:                "/var/lib/elasticsearch"
    path_logs:                "/var/log/elasticsearch"

    # bootstrap_memory_lock setting to false for use in development system
    bootstrap_memory_lock:    "false"
    es_network_hosts:         "{{ groups['es_masternodes'] | to_json }}"
    es_service_interface: "eth1"
    es_service_ip_address: "{{ hostvars[inventory_hostname]['ansible_' + es_service_interface].ipv4.address }}"
    # es_service_ip_address:    "0.0.0.0"

    # To create a dedicated master-eligible node when X-Pack is installed, set:
    node_master:       true
    node_data:         false
    node_ingest:       false
    node_ml:           false
    xpack_ml_enabled:  true
    xpack_security_enabled: yes

    # Master node majority
    discovery_zen_minimum_master_nodes: 2

    # Ownership and permissions for configfiles
    owner: "root"
    group: "elasticsearch"

    # TLS parameters
    #
    # zip archive name with P12 file
    elastic_ca_archive_name: "elasticstack"
    elastic_ca_password: "1234"

    xpack_security_transport_ssl_enabled: true
    xpack_security_transport_ssl_verification_mode: certificate
    xpack_security_transport_ssl_keystore_path: /etc/elasticsearch/ca/elasticstack/elasticstack.p12
    xpack_security_transport_ssl_truststore_path: /etc/elasticsearch/ca/elasticstack/elasticstack.p12

    # jvm.options
    jvm_initial_heap_size:   "512m"
    jvm_maximum_heap_size:   "512m"

    ### Temporary bootstrap password
    password_bootstrap:		"1234"

    ### Native accounts
    password_kibana:                "kibana"
    password_logstash_system:       "logstash"
    password_beats_system:          "ebeats"
    password_elastic:               "elastic"

    ### Useraccounts
    password_administrator:         "administrator"

  roles:
    # Masternode only runs Elasticsearch as master-eligable node
    - role: role_masternodes

- hosts:          es_logstashnodes
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

  vars:
    es_data_ports:         "9200"
    es_data_hosts:         "{{ groups['es_datanodes'] | to_json }}"

  roles:
    - role: role_logstash

- hosts:          es_kibananodes
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

#Assumes 1 kibana host and 1 elastic client, need to add some logic to deal with >1
  vars:
    kibana_server_port:                   "5601"
    kibana_server_host:                   "{{ groups['es_kibananodes'] | to_json }}"
    kibana_elasticsearch_url:             "{{ groups['es_clientnodes'] | to_json }}"
#Temporary, will use vault in future
    password_kibana:                      "kibana"

  roles:
    - role: role_kibana
