###
### Set up Kibananodes
###

- hosts:          es_kibananodes
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

#Assumes 1 kibana host and 1 elastic client, need to add some logic to deal with >1
  vars:
    kibana_server_port:                   "5601"
    kibana_server_host:                   "{{ ansible_eth1.ipv4.address }}"
    kibana_elasticsearch_url:             "{{ groups['es_clientnodes'][0] }}"
#Temporary, will use vault in future
    password_kibana:                      "kibana"

  roles:
    - role: role_kibana
