###
### Set up Logstashnodes
###


- hosts:          es_logstashnodes
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

  vars_files:
  - group_vars/all

  vars:
    es_data_ports:         "9200"
    es_data_hosts:         "{{ groups['es_datanodes'] | to_json }}"

    # Should be like this:
    # es_logstash_username:           "logstash_system"
    # password_logstash_system:       "{{password_logstash_system}}"

    # but temporarily using elastic user credentials, due to permission errors for out-of-the-box logstash_system role
    es_logstash_username:           "elastic"
    password_logstash_system:       "elastic"

    logstash_datacenter: "dc1"

    pipeline_filebeat_workers: "1"
    pipeline_metricbeat_workers: "1"
    pipeline_packetbeat_workers: "1"
    pipeline_heartbeat_workers: "1"

    pipeline_filebeat_queue: "persisted"
    pipeline_metricbeat_queue: "persisted"
    pipeline_packetbeat_queue: "persisted"
    pipeline_heartbeat_queue: "persisted"


  roles:
    - role: role_logstash
