###
### Set up Beats
###

- hosts:          es_beats
  remote_user:    vagrant
  become:         true
  become_user:    root
  become_method:  sudo
  gather_facts:   true

  vars_files:
  - group_vars/all
  - group_vars/logstashnodes

  roles:
    - role: role_metricbeats
    - role: role_filebeats
