###
### Set up the following:
### * CLIENT nodes
### * on client nodes issue API commands to set up native realm users

- hosts:         es_machinelearningnodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars_files:
  - group_vars/all
  - group_vars/machinelearningnodes
  - group_vars/tls

  roles:
    - role: role_machinelearningnodes
