###
### Set up TLS!
###

- hosts:         es_masternodes, es_datanodes, es_clientnodes, es_machinelearningnodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars_files:
  - group_vars/all
  - group_vars/tls

  roles:
    # Set up TLS for transport protocol on ALL cluster nodes
    - role: role_tls
    - role: role_filerealm
