###
### Set up the following:
### * CLIENT nodes
### * on client nodes issue API commands to set up native realm users

- hosts:         es_clientnodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars_files:
  - group_vars/all
  - group_vars/clientnodes
  - group_vars/tls


  roles:
    # Masternode only runs Elasticsearch as master-eligable node
    - role: role_clientnodes
