###
### Set up the following:
### * DATA nodes

- hosts:         es_datanodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  vars_files:
  - group_vars/all
  - group_vars/datanodes
  - group_vars/tls

  roles:
    - role: role_datanodes
