###
### Start Kibana at boot time
###

  - name: Start and enable Kibana at boot time
    service:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - kibana
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"

###
### Kibana config file
###

  - name: Templating Kibana config file
    template:
      src: templates/kibana.yml.j2
      dest: "/etc/kibana/kibana.yml"
    notify:
      - restart kibana
    tags:
      - kibana-configfiles
