###
### Add repo if we can connect to the internet
###

  - name: Add Elasticsearch repo
    yum_repository:
      name: Elasticsearch repository for 6.x package
      description: Elasticsearch repo
      baseurl: https://artifacts.elastic.co/packages/6.x/yum
      gpgcheck: 1
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled: 1
    when: es_use_repository

###
### Elasticsearch installation
###
  - name: install Kibana
    yum:
      name: kibana
      state: present
    notify: restart kibana

###
### Kibana config file
###

  - name: Templating Kibana config file
    template:
      src: templates/kibana.yml.j2
      dest: "/etc/kibana/kibana.yml"
    notify:
      - restart kibana
    tags:
      - kibana-configfiles

###
### Start Kibana at boot time
###

  - name: Start and enable Kibana at boot time
    service:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - kibana
    when:
      - inventory_hostname in groups['es_kibananodes']
    tags:
      - kibana-configfiles
