#clustername:              "cluster_dc1_dev"
#path_data:                "/var/lib/elasticsearch"
#path_logs:                "/var/log/elasticsearch"
#bootstrap_memory_lock:    "true"

# To create a dedicated master-eligible node when X-Pack is installed, set:
#node_master:       true
#node_data:         false
#node_ingest:       false
#node_ml:           false
#xpack_ml_enabled:  true

# Master node majority
#discovery_zen_minimum_master_nodes: 2

# Ownership and permissions for configfiles
#owner: "root"
#group: "elasticsearch"

# IP addresses
#es_mgmt_interface: "eth0"
#es_service_interface: "eth1"
#es_mgmt_ip_address: "{{ hostvars[inventory_hostname]['ansible_' + es_mgmt_interface].ipv4.address }}"
#es_service_ip_address: "{{ hostvars[inventory_hostname]['ansible_' + es_service_interface].ipv4.address }}"


# IP addresses for all hosts
#ip_master_01: "{{ hostvars[groups['dc1_masternodes'][0]]['ansible_' + es_service_interface]['ipv4']['address'] }}"
#ip_master_02: "{{ hostvars[groups['dc1_masternodes'][1]]['ansible_' + es_service_interface]['ipv4']['address'] }}"
#ip_master_03: "{{ hostvars[groups['dc1_masternodes'][2]]['ansible_' + es_service_interface]['ipv4']['address'] }}"

#ip_master_01: "{{ hostvars['dc1_es_master_01']['ansible_' + es_service_interface]['ipv4']['address'] }}"
#ip_master_02: "{{ hostvars['dc1_es_master_02']['ansible_' + es_service_interface]['ipv4']['address'] }}"
#ip_master_03: "{{ hostvars['dc1_es_master_03']['ansible_' + es_service_interface]['ipv4']['address'] }}"
