############################ FILEBEAT ###########################
###
### Filebeat modules
###



# It can happen that services are restarted too often, requiring a reset
 #RESET service filebeat
  - name: RESET failed beat services
    command: "systemctl reset-failed {{ item }}.service"
    with_items:
      - filebeat
    when:
      - inventory_hostname in groups['es_beats']
    tags:
      - filebeat-modules
      - filebeat

###
### Filebeat config file
###

  - name: Templating Filebeat config file
    template:
      src: templates/filebeat.yml.j2
      dest: "/etc/filebeat/filebeat.yml"
      mode: 0750
      owner: "{{ owner }}"
      group: "{{ group }}"
    notify:
      - restart filebeat
    when:
      - inventory_hostname in groups['es_beats']
    tags:
      - filebeat-configfiles
      - filebeat

# Enable filebeat modules
  - name: Enable generic filebeat modules
    command: /usr/bin/filebeat modules enable {{ item }}
    with_items:
      - apache2
      - auditd
      - mysql
      - system
    when:
      - inventory_hostname in groups['es_beats']
    tags:
      - filebeat-modules
      - filebeat

## Enable filebeat modules
  - name: Enable logstash filebeat module on logstash nodes
    command: /usr/bin/filebeat modules enable {{ item }}
    with_items:
      - logstash
    when:
      - inventory_hostname in groups['es_beats']
      - inventory_hostname in groups['es_logstashnodes']
    tags:
      - filebeat-modules
      - filebeat


###
### Start Filebeat at boot time
###

  - name: Start and enable Filebeat at boot time
    service:
      name: "{{ item }}"
      state: restarted
      enabled: True
    with_items:
      - filebeat
    when:
      - inventory_hostname in groups['es_beats']
    tags:
      - filebeat-start
      - filebeat
