###
### Description of task
###

# In this main.yml file the following actions will be performed on the master nodes
#
# - templating elasticsearch.yml config file
# - templating jvm.options config file
# - starting elasticsearch processes
# - wait for port 9200 to become available (= wait_for completion of elasticsearch startup)

###
### Add repo if we can connect to the internet
###

  - name: Add Elasticsearch repo
    yum_repository:
      name: Elasticsearch repository for 6.x package
      description: Elasticsearch repo
      baseurl: https://artifacts.elastic.co/packages/6.x/yum
      gpgcheck: 1
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled: 1
    when: es_use_repository

###
### Elasticsearch installation
###
  - name: install Elasticsearch
    yum:
      name: elasticsearch-{{ es_version }}
      state: present
    notify: restart elasticsearch

###
### Elasticsearch config file
###

  - name: Templating Elasticsearch config file
    template:
      src: templates/elasticsearch.yml.j2
      dest: "/etc/elasticsearch/elasticsearch.yml"
    tags:
      - elasticsearch-configfiles
      - elasticsearch-firststart

###
### Elasticsearch jvm.options file
###

  - name: Templating JVM config file
    template:
      src: templates/jvm.options.j2
      dest: "/etc/elasticsearch/jvm.options"
    tags:
      - elasticsearch-configfiles
      - elasticsearch-firststart

###
### Start Elasticsearch at boot time
###

  - name: Start and enable Elasticsearch on master nodes at boot time
    service:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - elasticsearch
    when:
      - inventory_hostname in groups['es_masternodes']
    tags:
      - elasticsearch-configfiles
      - elasticsearch-firststart


  - name: Wait for Elasticsearch port 9200 to become available on master nodes
    wait_for:
      host: "{{ es_service_ip_address }}"
      port: 9200
      state: started
      delay: 5
      connect_timeout: 5
      timeout: "{{ wait_for_timeout }}"
    when:
      - inventory_hostname in groups['es_masternodes']
    tags:
      - elasticsearch-configfiles
      - elasticsearch-firststart
