###
### Start beats at boot time
###

  - name: Start and enable beats at boot time
    service:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - filebeat
       - heartbeat-elastic
       - metricbeat
       - packetbeat
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"

  - name: Templating Elasticsearch config file
    template:
      src: templates/metricbeat.yml.j2
      dest: "/etc/metricbeat/metricbeat.yml"
    notify:
     - restart metricbeat
    tags:
     - metricbeat-configfiles
